#!/bin/bash
# Routine A — The Drafter
# Gathers repo activity and posts a digest to the tracking issue.
#
# Trigger: manual (bash routine-a.sh), cron, or GitHub Actions
# Uses: opencode run, git, gh

set -euo pipefail

TRACKING_ISSUE=${TRACKING_ISSUE:-1}
REPO_ROOT=$(git rev-parse --show-toplevel)

echo "=== Daily Digest — $(date +%Y-%m-%d) ==="
echo "Tracking issue: #$TRACKING_ISSUE"
echo

# Gather data
echo "Gathering commits from the last 24 hours..."
COMMITS=$(git log --since="1 day ago" --oneline --no-merges 2>/dev/null || echo "(none)")

echo "Gathering open issues..."
ISSUES=$(gh issue list --state open --limit 10 2>/dev/null || echo "(unable to fetch)")

echo "Gathering open PRs..."
PRS=$(gh pr list --state open --limit 10 2>/dev/null || echo "(unable to fetch)")

# Build the digest
DIGEST="## 📋 Daily Digest — $(date +%Y-%m-%d)

### Commits (last 24h)
\`\`\`
${COMMITS}
\`\`\`

### Open Issues
\`\`\`
${ISSUES}
\`\`\`

### Open PRs
\`\`\`
${PRS}
\`\`\`

---
*Generated by Routine A (OpenCode). Review before approving.*"

# Post to tracking issue
echo
echo "Posting digest to issue #$TRACKING_ISSUE..."
gh issue comment "$TRACKING_ISSUE" --body "$DIGEST"

echo
echo "✅ Digest posted. Review it at:"
echo "   gh issue view $TRACKING_ISSUE --comments"
echo
echo "If approved, fire Routine B:"
echo "   curl -X POST http://localhost:8080/approve \\"
echo "     -H \"Authorization: Bearer \$APPROVAL_TOKEN\" \\"
echo "     -H \"Content-Type: application/json\""
