#!/bin/bash
# Dreaming Loop — reads other loops' logs, proposes rule changes as a PR
#
# Trigger: weekly cron, or manual: bash dream.sh
# Uses: git, gh, grep, date

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPOS_FILE="$SCRIPT_DIR/REPOS.md"
STATE_FILE="$SCRIPT_DIR/dreaming-state.md"
RULES_FILE="$SCRIPT_DIR/rules.md"

echo "=== Dreaming Loop — $(date +%Y-%m-%d) ==="
echo

# 1. Read last analysis date from spine
if [ ! -f "$STATE_FILE" ]; then
    echo "ERROR: dreaming-state.md not found"
    exit 1
fi

LAST_ANALYSIS=$(grep "last_analysis:" "$STATE_FILE" | grep -v "YYYY" | awk '{print $2}' | head -1)
echo "Last analysis: $LAST_ANALYSIS"
echo

# 2. Read repos to watch
if [ ! -f "$REPOS_FILE" ]; then
    echo "ERROR: REPOS.md not found"
    exit 1
fi

echo "Scanning repos..."
FAILURES=""

while IFS= read -r line; do
    # Skip comments and empty lines
    [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
    
    # Extract path
    PROGRESS_PATH=$(echo "$line" | sed 's/^- //' | xargs)
    FULL_PATH="$SCRIPT_DIR/$PROGRESS_PATH"
    
    if [ ! -f "$FULL_PATH" ]; then
        echo "  ⚠ $PROGRESS_PATH not found, skipping"
        continue
    fi
    
    echo "  Checking $PROGRESS_PATH..."
    
    # Get entries since last analysis
    ENTRIES=$(awk -v date="$LAST_ANALYSIS" '
        /^- [0-9]{4}-[0-9]{2}-[0-9]{2}/ {
            entry_date = substr($0, 3, 10)
            if (entry_date > date) print
        }
    ' "$FULL_PATH" 2>/dev/null || true)
    
    if [ -z "$ENTRIES" ]; then
        echo "    No new entries since $LAST_ANALYSIS"
        continue
    fi
    
    # Find failures
    FAIL_LINES=$(echo "$ENTRIES" | grep -i "FAIL\|error\|forgot\|missed" || true)
    
    if [ -n "$FAIL_LINES" ]; then
        echo "    Found failures:"
        echo "$FAIL_LINES" | while IFS= read -r fail; do
            echo "      $fail"
        done
        FAILURES="$FAILURES
$FAIL_LINES"
    fi
    
done < <(grep "^-" "$REPOS_FILE")

echo

# 3. Analyze for repeated patterns
if [ -z "$FAILURES" ]; then
    echo "No failures found. Nothing to propose."
    
    # Update spine
    cat > "$STATE_FILE" << EOF
# Dreaming State — the spine

This file is the spine for the dreaming loop. It tracks what's been analyzed
and prevents re-analysis. Read it first, write it last.

## Format

\`\`\`yaml
last_analysis: YYYY-MM-DD
analyzed_entries:
  - repo: path/to/progress.md
    entries_analyzed: N
    failures_found: N
    proposals_made: N
\`\`\`

## Current state

\`\`\`yaml
last_analysis: $(date +%Y-%m-%d)
analyzed_entries: []
\`\`\`

## History

- $(date +%Y-%m-%d) status=OK failures=0 proposals=0 (no failures found)
EOF
    
    exit 0
fi

echo "=== Analyzing failure patterns ==="
echo

# Count failure patterns
echo "$FAILURES" | grep -oP "reason='[^']+'" | sort | uniq -c | sort -rn | head -5

# Find the most common failure
MOST_COMMON=$(echo "$FAILURES" | grep -oP "reason='[^']+'" | sort | uniq -c | sort -rn | head -1)

if [ -z "$MOST_COMMON" ]; then
    echo "No clear pattern found."
    exit 0
fi

COUNT=$(echo "$MOST_COMMON" | awk '{print $1}')
REASON=$(echo "$MOST_COMMON" | sed "s/^ *[0-9]* *reason='//" | sed "s/'$//")

echo
echo "Most common failure ($COUNT times): $REASON"
echo

# 4. Draft the smallest rules.md change
echo "=== Drafting rules change ==="
echo

# Create a branch
BRANCH="claude/dreaming-loop-$(date +%Y%m%d)"
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Append the new rule
echo "" >> "$RULES_FILE"
echo "## Auto-generated by dreaming loop" >> "$RULES_FILE"
echo "- $(date +%Y-%m-%d): $REASON (appeared $COUNT times in logs)" >> "$RULES_FILE"

echo "Proposed change to rules.md:"
echo "---"
tail -5 "$RULES_FILE"
echo "---"
echo

# 5. Create PR with evidence
echo "=== Creating PR ==="
echo

# Build PR body with evidence
PR_BODY="## Dreaming Loop Proposal

### Evidence

This proposal is based on $COUNT occurrences of the same failure pattern:

\`\`\`
$FAILURES
\`\`\`

### Proposed change

Added rule: \`$REASON\`

This rule would prevent this failure pattern in future runs.

### Why this line

The failure appeared $COUNT times across analyzed logs. Each occurrence
represents a run that could have been prevented with this rule.

### Deletion proposed

None — this is an addition only.

---
*Generated by dreaming loop on $(date +%Y-%m-%d)*"

# Commit and push
git add rules.md
git commit -m "dreaming-loop: add rule for repeated failure pattern

Evidence: $COUNT occurrences of '$REASON' in analyzed logs.

$PR_BODY"

git push origin "$BRANCH" 2>/dev/null || echo "Note: push failed (may need to set remote)"

# Create PR
gh pr create \
    --title "dreaming-loop: Add rule for repeated failure ($COUNT occurrences)" \
    --body "$PR_BODY" \
    --head "$BRANCH" \
    2>/dev/null || echo "Note: PR creation failed (may need gh auth)"

echo
echo "✅ PR created on branch $BRANCH"

# 6. Update dreaming-state.md
echo
echo "=== Updating spine ==="

cat > "$STATE_FILE" << EOF
# Dreaming State — the spine

This file is the spine for the dreaming loop. It tracks what's been analyzed
and prevents re-analysis. Read it first, write it last.

## Format

\`\`\`yaml
last_analysis: YYYY-MM-DD
analyzed_entries:
  - repo: path/to/progress.md
    entries_analyzed: N
    failures_found: N
    proposals_made: N
\`\`\`

## Current state

\`\`\`yaml
last_analysis: $(date +%Y-%m-%d)
analyzed_entries:
  - repo: docs-freshness/progress.md
    entries_analyzed: $(echo "$FAILURES" | wc -l)
    failures_found: $(echo "$FAILURES" | grep -c "FAIL" || echo 0)
    proposals_made: 1
\`\`\`

## History

- $(date +%Y-%m-%d) status=OK failures=$(echo "$FAILURES" | wc -l) proposals=1 (proposed rule for: $REASON)
EOF

echo "Spine updated."
echo
echo "=== Done ==="
echo "Review the PR at: gh pr list --state open"
echo "Merge if the evidence is solid. Close if it's not."
